# Generated by Django 4.0.3 on 2022-05-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kulube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('il', models.CharField(max_length=50)),
                ('ilce', models.CharField(max_length=100)),
                ('mahalle', models.CharField(max_length=100)),
                ('sokak', models.CharField(max_length=100)),
                ('kapi', models.CharField(max_length=50)),
                ('aciklama', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('sontarih', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sayac', models.IntegerField(default=1)),
                ('img', models.CharField(default='8.jpeg', max_length=100)),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
                ('dogcat', models.CharField(default='Kedi', max_length=20)),
            ],
            options={
                'ordering': ['sontarih'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('beslemesayisi', models.IntegerField(default=0)),
                ('bildirmesayisi', models.IntegerField(default=0)),
                ('mamakilo', models.IntegerField(default=0)),
                ('auth_token', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-beslemesayisi'],
            },
        ),
    ]
