# Generated by Django 4.0.3 on 2022-04-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kulube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('il', models.CharField(max_length=50)),
                ('ilçe', models.CharField(max_length=100)),
                ('mahalle', models.CharField(max_length=100)),
                ('sokak', models.CharField(max_length=100)),
                ('kapı', models.CharField(max_length=50)),
                ('acıklama', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('sontarih', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sayac', models.IntegerField(default=1, null=True)),
                ('img', models.CharField(max_length=100, null=True)),
                ('latitude', models.CharField(max_length=20, null=True)),
                ('longitude', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('beslemesayısı', models.IntegerField(default=0, null=True)),
                ('bildirmesayısı', models.IntegerField(default=0, null=True)),
                ('mamakilo', models.IntegerField(default=0, null=True)),
                ('auth_token', models.CharField(max_length=100, null=True)),
            ],
            options={
                'ordering': ['beslemesayısı'],
            },
        ),
    ]
