# Generated by Django 4.0.3 on 2022-04-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harita', '0003_alter_kulube_dogcat_alter_kulube_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kulube',
            name='img',
            field=models.CharField(default='4.jpeg', max_length=100),
        ),
        migrations.AlterField(
            model_name='kulube',
            name='sayac',
            field=models.IntegerField(default=0),
        ),
    ]
