# Generated by Django 4.0.3 on 2022-04-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harita', '0004_alter_kulube_img_alter_kulube_sayac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kulube',
            name='img',
            field=models.CharField(default='5.jpeg', max_length=100),
        ),
        migrations.AlterField(
            model_name='kulube',
            name='sayac',
            field=models.IntegerField(null=True),
        ),
    ]
