# Generated by Django 4.0.3 on 2022-05-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harita', '0006_alter_kulube_img_alter_kulube_sayac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kulube',
            name='img',
            field=models.CharField(default='2.jpeg', max_length=100),
        ),
    ]
